### ISSUE TITLE
请问怎么使用命令行进行commit？

### ISSUE THREAD

**Issue by Fairy-Jie** [NEUP-Net-Depart/mengxin-2018#103]
如题。TUT

**Comment by Swinggcat** [comment]
> ![图](https://user-images.githubusercontent.com/32394722/46682661-c02d1580-cc20-11e8-86ff-4811ece67d3a.png)


通读所提供的 Git 参考资料中的任意一个，你就会得到答案。
如果还不知道资料在哪里，请点开[这里](https://github.com/NEUP-Net-Depart/mengxin-2018/tree/ae07462e04a2f44ca6adbf1fcbe7a6714e591445)，定位到图示区域。
