### ISSUE TITLE
建议添加 `Comments and Wishes` Section

### ISSUE THREAD

**Issue by Swinggcat** [NEUP-Net-Depart/mengxin-2018#44]
Forwarded from @VOID001 :
> 让大家说说想要在后面的培训中学习什么，以及得到什么提高。

**Comment by VOID001** [comment]
Well, it will be proper to discuss these comments and wishes with Github Issue. Issue list is better for discussing.
You can add a label and tagged all issues of this type.

**Comment by DuckSoft** [comment]
That shall be fine. I'll do it now.
