### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by SantaSati** [NEUP-Net-Depart/mengxin-2018#99]
# # git push
      remote: Permission to NEUP-Net-Depart/mengxin-2018.git denied to ****.
      fatal: unable to access 'https://****：>>>>@github.com/NEUP-Net-Depart/mengxin-2018/': The       requested URL returned error: 403
      problem:I can't solve it.
    ##tip:**** is username,>>>> is key.

**Comment by VOID001** [comment]
@SantaSati You don't have permission to direct push in this repo

**Comment by SantaSati** [comment]
I built  a new branch and then I merged them .At last,I committed ,pushed and got that:
$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
What should I do next ，and Is any error has happend？

**Comment by wanghaiwei** [comment]
see you upstream address. and if it is up-to-date. it's ok.

**Comment by VOID001** [comment]
> I built a new branch and then I merged them .At last,I committed ,pushed and got that:
You cannot use command line git to merge your modification into this repo, you need to open a pull request.
> $ git status
> On branch master
> Your branch is up to date with 'origin/master'.
This means your branch is the same as the remote branch. check what your remote address is. It probably be the address to your forked repo
> nothing to commit, working tree clean
> What should I do next ，and Is any error has happend？
You need to open a PR(pull request) to submit your changes to this repo

**Comment by DuckSoft** [comment]
Now that problem is solved, closing issue now!
